// apps/vite-app/src/components/Footer.tsx

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import './Footer.css';
import { faBilibili, faFacebook, faGithub, faGitlab, faGoogleScholar, faInstagram, faLinkedin, faYoutube } from '@fortawesome/free-brands-svg-icons';
import { faEnvelope } from '@fortawesome/free-solid-svg-icons';
import { useEffect, useState } from 'react';

export function Footer() {
    const [clickCount, setClickCount] = useState(0);

    useEffect(() => {
        if (localStorage.getItem('start-debug-listener') !== 'true') {
            return;
        }
        if (clickCount === 3) {
            if (localStorage.getItem('enable-debug') !== 'true') {
                localStorage.setItem('enable-debug', 'true');
                localStorage.removeItem('start-debug-listener');
                alert('Debug mode enabled!');
                window.location.reload();
            } else {
                localStorage.setItem('enable-debug', 'false');
                localStorage.removeItem('start-debug-listener');
                alert('Debug mode disabled!');
                window.location.reload();
            }
        }
    }, [clickCount]);
    return (
        <footer className="footer">
            <div className="social-icons">
                <a href="https://space.bilibili.com/30023942" className="social-icon" title="bilibili">
                    <FontAwesomeIcon icon={faBilibili} size="2x" />
                </a>
                <a href="mailto:admin@techzjc.com" className="social-icon" title="email">
                    <FontAwesomeIcon icon={faEnvelope} size="2x" />
                </a>
                <a href="https://www.facebook.com/techzjc" className="social-icon" title="facebook">
                    <FontAwesomeIcon icon={faFacebook} size="2x" />
                </a>
                <a href="https://git.cs.vt.edu/techzjc" className="social-icon" title="gitlab">
                    <FontAwesomeIcon icon={faGitlab} size="2x" />
                </a>
                <a href="https://github.com/g497813927" className="social-icon" title="github">
                    <FontAwesomeIcon icon={faGithub} size="2x" />
                </a>
                <a href="https://scholar.google.com/citations?user=bfAU2pYAAAAJ" className="social-icon" title="google-scholar">
                    <FontAwesomeIcon icon={faGoogleScholar} size="2x" />
                </a>
                <a href="https://www.instagram.com/techzjc/" className="social-icon" title="instagram">
                    <FontAwesomeIcon icon={faInstagram} size="2x" />
                </a>
                <a href="https://www.linkedin.com/in/techzjc/" className="social-icon" title="linkedin">
                    <FontAwesomeIcon icon={faLinkedin} size="2x" />
                </a>
                <a href="https://www.youtube.com/@techzjc" className="social-icon" title="youtube">
                    <FontAwesomeIcon icon={faYoutube} size="2x" />
                </a>
            </div>
            <p
                id="copyright" 
                className={localStorage.getItem('start-debug-listener') === 'true' ? 'disable-select' : ''}
                onClick={() => {
                    if (localStorage.getItem('start-debug-listener') === 'true') {
                        setClickCount(prevCount => prevCount + 1);
                        setTimeout(() => {
                            setClickCount(0);
                        }, 1000);
                    }
                }}
            >© 2016-{new Date().getFullYear()} Techzjc 版权所有</p>
            <div style={{
                margin: '0 auto',
                padding: '20px 0'
            }}>
                <a href="https://beian.miit.gov.cn/" target="_blank" rel="noopener" style={{
                    display: 'inline-block',
                    textDecoration: 'none',
                    height: '20px',
                    lineHeight: '20px',
                    margin: '0px 0px 0px 5px',
                    color: "white"
                }}>浙ICP备2020032105号</a>
                <span>    |    </span>
                <a target="_blank" rel="noopener" href="http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=33010402004325" style={{
                    display: 'inline-block',
                    textDecoration: 'none',
                    height: '20px',
                    lineHeight: '20px'
                }}><img src="https://static.techzjc.com/icon/icon-beian.webp" style={{
                    float: 'left'
                }} alt="公安联网备案" /><div style={{
                    float: 'left',
                    height: '20px',
                    lineHeight: '20px',
                    margin: '0px 0px 0px 5px',
                    color: 'white'
                }}>浙公网安备 33010402004325号</div></a>
            </div>
        </footer>
    )
}

// src/components/Footer.vue
<script setup>
import {ref} from "vue";

const currentYear = new Date().getFullYear()
const language = ref('auto')
const ICP_NUMBER = ref('浙ICP备2020032105号')

const CHINA_BEI_AN_NUMBER = ref('浙公网安备 33010402004325号')

const CHINA_BEI_AN_REF_URL = ref('http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=33010402004325')

</script>

<template>
  <div class="footer">
    <div class="social-media">
      <a href="https://space.bilibili.com/30023942" class="icon"><img
          src="https://static.techzjc.com/icon/icon-bilibili-white.svg" class="icon-img"/></a>
      <a href="https://www.facebook.com/techzjc" class="icon"><img
          src="https://static.techzjc.com/icon/icon-facebook-white.svg" class="icon-img"/></a>
      <a href="https://github.com/g497813927" class="icon"><img
          src="https://static.techzjc.com/icon/icon-GitHub-white.svg" class="icon-img"/></a>
      <a href="https://www.instagram.com/techzjc/" class="icon"><img
          src="https://static.techzjc.com/icon/icon-Instagram-white.svg" class="icon-img"/></a>
      <a href="https://www.youtube.com/channel/UC_UevpLekFBbIRv7wWEMe7w" class="icon"><img
          src="https://static.techzjc.com/icon/icon-YouTube-white.svg" class="icon-img"/></a>
    </div>
    <p>友情链接 ｜ Credits</p>
    <p>© 2016-{{ currentYear }} Techzjc 版权所有</p>
    <div class="china-icp-info">
      <a href="https://beian.miit.gov.cn/" target="_blank" class="china-miit-icp-style">{{ ICP_NUMBER }}</a>
      <span>    |    </span>
      <a target="_blank" :href="CHINA_BEI_AN_REF_URL" class="china-bei-an-style"><img
          src="https://static.techzjc.com/icon/icon-beian.png" alt="公安联网备案图标"/>
        <div>
          {{ CHINA_BEI_AN_NUMBER }}
        </div>
      </a>
    </div>
  </div>

</template>

<style scoped>
.footer {
  background-color: #000000;
  color: #ffffff;
  text-align: center;
  padding: 3em;
}

.social-media {
  margin-bottom: 1em;
}

.icon {
  margin: 0 0.1em;
}

.icon-img {
  width: 32px;
}

.china-icp-info {
  margin: 0 auto;
  padding: 20px 0;
}

.china-miit-icp-style {
  display: inline-block;
  text-decoration: none;
  height: 20px;
  line-height: 20px;
  margin: 0 0 0 5px;
  color: #ffffff;
}

.china-bei-an-style {
  display: inline-block;
  text-decoration: none;
  height: 20px;
  line-height: 20px;
}

.china-bei-an-style img {
  float: left;
}

.china-bei-an-style div {
  float:left;
  height:20px;
  line-height:20px;
  margin: 0 0 0 5px;
  color: #ffffff
}


</style>
